[build]
  command = """
  git clone https://github.com/flutter/flutter.git -b stable
  export PATH="$PATH:`pwd`/flutter/bin"
  flutter config --enable-web
  flutter build web --release
  """
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "3.24.0"
